name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.6.0
homepage: https://github.com/leisim/dartx

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  path: ^1.8.0
  crypto: ^3.0.0
  characters: ^1.1.0 
  time: ^1.5.0-nullsafety.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
  fake_async: ^1.2.0